### ISSUE TITLE
Error With No Values

### ISSUE THREAD

**Issue by aljawaid** [creecros/kbphpimap#7]
This error is after installing (folder starts with capital K), and when accessing `Task Email` sidebar menu inside a task.  no mailbox details have been entered in settings yet.
```
[php7:error] [pid 1183151] [client 86.000.166.135:59386] PHP Fatal error:  Uncaught Error: Undefined constant 'OP_READONLY' in /var/www/my.domain/public_html/plugins/Kbphpimap/Controller/EmailViewController.php:180
```

**Comment by creecros** [comment]
that's a different error, and it's because your server doesn't have php-imap installed.

**Comment by creecros** [comment]
you also need php81-fileinfo

I put all this under requirements in the Readme

**Comment by aljawaid** [comment]
oh ok, I gnored it as i am not using docker, will look into it

**Comment by creecros** [comment]
I dont know your os, but the docker uses alpine.

if you are Debian, it would be apt install, you need to find the right package for your os. probably still php-imap, and assuming your php 8.1, then php81-fileinfo. just guessing.

**Comment by aljawaid** [comment]
done it, also updated the readme for my php version, but still same error.  I will put some email settings in and see how i get on

**Comment by creecros** [comment]
the OP_READONLY is a php-imap constant.
