### ISSUE TITLE
CommentOnTask ignores the subject

### ISSUE THREAD

**Issue by alfredbuehler** [creecros/kbphpimap#8]
The subject might contain a summary of the comment, which is important information. 
It should be included in the comment.

**Comment by creecros** [comment]
I am not against it. just wasn't sure how at the time. I guess combine it with the message.

**Comment by alfredbuehler** [comment]
Fixed by [b8ae336](https://github.com/creecros/kbphpimap/commit/b8ae33674b49708601b5021dce7850af997c648a).
The comment now includer the subject as headline.
![image](https://user-images.githubusercontent.com/2079289/217030439-f679325a-0cf7-4215-823d-c383bf4e9612.png)
